--##################
--## KEYBINDINGS ###
--##################

local programs = require("programs")

-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- ======= Focus movement / Frequent programs =========

-- ------- Focus movement -------
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + I", hl.dsp.layout("cyclenext"))
hl.bind(mainMod .. " + U", hl.dsp.layout("cycleprev"))

-- ------- frequent Programs -------
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("firefox -P no-navbar"))
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(programs.menu))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd("hyprpicker"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(programs.terminal))

-- Screenshoting
hl.bind(mainMod .. " + SHIFT + PRINT", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot-active-monitor.sh"))
hl.bind(mainMod .. " + CONTROL + PRINT", hl.dsp.exec_cmd("grim - | wl-copy"))

-- ======= Window movement =========
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pin())

hl.bind(mainMod .. " + ALT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + ALT + U", hl.dsp.exec_cmd("~/.config/hypr/scripts/roll-keep-mfact.sh rollnext"))
hl.bind(mainMod .. " + ALT + X", hl.dsp.exec_cmd("~/.config/hypr/scripts/roll-keep-mfact.sh rollnext"))
hl.bind(mainMod .. " + ALT + I", hl.dsp.exec_cmd("~/.config/hypr/scripts/roll-keep-mfact.sh rollprev"))
hl.bind(mainMod .. " + ALT + C", hl.dsp.exec_cmd("~/.config/hypr/scripts/roll-keep-mfact.sh rollprev"))

-- ======= Workspaces =========

-- ------- 1-10 -------
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("~/.config/hypr/scripts/cycle-workspace.sh next"))
hl.bind(mainMod .. " + ALT + TAB", hl.dsp.exec_cmd("~/.config/hypr/scripts/cycle-workspace.sh prev"))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + ALT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + ALT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + ALT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + ALT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + ALT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + ALT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + ALT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + ALT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + ALT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + ALT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

-- ------- special -------
hl.bind(mainMod .. " + A", hl.dsp.workspace.toggle_special("ai"))
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("scratchpad"))
hl.bind(mainMod .. " + D", hl.dsp.workspace.toggle_special("comms"))

hl.bind(mainMod .. " + ALT + A", hl.dsp.window.move({ workspace = "special:ai", follow = false }))
hl.bind(mainMod .. " + ALT + S", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }))
hl.bind(mainMod .. " + ALT + D", hl.dsp.window.move({ workspace = "special:comms", follow = false }))

-- ======= Layout changes =========
hl.bind(mainMod .. " + CONTROL + M", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-master.sh"))

hl.bind(mainMod .. " + CONTROL + U", hl.dsp.exec_cmd("~/.config/hypr/scripts/adjust-mfact.sh -0.05"))
hl.bind(mainMod .. " + CONTROL + I", hl.dsp.exec_cmd("~/.config/hypr/scripts/adjust-mfact.sh +0.05"))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

-- ------- Master ------
hl.bind(mainMod .. " + CONTROL + H", hl.dsp.layout("orientationleft"))
hl.bind(mainMod .. " + CONTROL + J", hl.dsp.layout("orientationtop"))
hl.bind(mainMod .. " + CONTROL + L", hl.dsp.layout("orientationright"))
hl.bind(mainMod .. " + CONTROL + K", hl.dsp.layout("orientationbottom"))
hl.bind(mainMod .. " + CONTROL + O", hl.dsp.layout("orientationcenter"))

-- ======= Other =========
hl.bind(mainMod .. " + CONTROL + BACKSPACE", hl.dsp.exec_cmd("hyprlock"))

hl.bind("F1", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

hl.bind("F2", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"))
hl.bind("F3", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+"))

hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("brightnessctl set 5%-"))
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd("brightnessctl set 5%+"))

hl.bind(mainMod .. " + CONTROL + F10", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-waybar.sh"))
hl.bind(mainMod .. " + CONTROL + F11", hl.dsp.exit())
hl.bind(mainMod .. " + CONTROL + F12", hl.dsp.exec_cmd("systemctl poweroff"))
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("makoctl dismiss -a"))
hl.bind(mainMod .. " + ALT + ESCAPE", hl.dsp.exec_cmd("makoctl mode -t do-not-disturb"))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

