-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1
-- windowrule = float, ^(kitty)$

-- Example windowrule v2
-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "specify-discord-workspace",
    match = {
        class = "^(discord)$",
    },
    workspace = "special:comms",
})

hl.window_rule({
    name = "specify-telegram-workspace",
    match = {
        class = "^(org.telegram.desktop)$",
    },
    workspace = "special:comms",
})

hl.window_rule({
    name = "specify-slack-workspace",
    match = {
        class = "^(Slack)$",
    },
    workspace = "special:comms",
})

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
    name = "ignore-maximize-requests",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name = "fix-xwayland-dragging",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})

-- Float and center popups
hl.window_rule({
    name = "float-popups",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    float = true,
    center = true,
    size = "1000 600",
})

hl.window_rule({
    name = "float-gimp-export",
    match = {
        initial_class = "^(file-png)$",
    },
    float = true,
    center = true,
    size = "1000 600",
})

-- Tile godot project manager and engine
hl.window_rule({
    name = "tile-godot",
    match = {
        initial_class = "^(Godot)$",
        initial_title = "^(Godot)$",
    },
    float = false,
})

-- Float godot game window
hl.window_rule({
    name = "float-godot-game",
    match = {
        initial_class = "negative:^(Godot)$",
        initial_title = "^(Godot)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name = "tile-aseprite",
    match = {
        class = "^(Aseprite)$",
    },
    float = false,
})

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "2",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1",
})


